### ISSUE TITLE
filechannel用transferTo报错

### ISSUE THREAD

**Issue by zhyhzz** [zhyhzz/zhyhzz.github.io#1]
```
public static void main(String[] args) {
        try(FileChannel from = new FileInputStream("from.txt").getChannel();
            FileChannel to = new FileInputStream("to.txt").getChannel();
        ) {
            from.transferTo(0, from.size(), to);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

```
`Exception in thread "main" java.nio.channels.NonWritableChannelException
	at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:595)
	at cn.zhy.netty.c1.TestFileChannelTransferTo.main(TestFileChannelTransferTo.java:13)`

**Comment by zhyhzz** [comment]
` else if (var5 instanceof FileChannelImpl && !((FileChannelImpl)var5).writable) {
            throw new NonWritableChannelException();`
这里不能通过FileInputStream去获取通道，因为获取到的通道是只读的，用
```
FileChannel from = new RandomAccessFile("from.txt", "rw").getChannel();
FileChannel to = new RandomAccessFile("to.txt", "rw").getChannel();
```
